### ISSUE TITLE
binaries? install instructions?

### ISSUE THREAD

**Issue by ptitle** [simonwhelan/seqfilter#7]
Hi,

I'm very interested in trying out this method, but I don't see any binaries available under Releases. I'm also not quite sure how to install from source. For what it's worth, I'm on a Apple M2 macbook pro. Could you please provide some source install instructions?
Thanks!

**Comment by ptitle** [comment]
With some help, I was able to compile this by editing the Makefile and replacing `-mfpmath=sse` and `-msse2`, and then running `make all`.

**Comment by simonwhelan** [comment]
Apologies for not getting back sooner and I'm pleased you've both solved the issue and shared the solution. I hope Prequal works well for you.
